name: Dummy Environment Print (manual)

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - DEVELOPMENT
          - PRODUCTION

jobs:
  print:
    runs-on: ubuntu-latest
    # kör i valt environment (måste finnas under Settings → Environments)
    environment: ${{ inputs.env }}
    steps:
      - name: Print environment
        run: echo "Deploy to ${{ inputs.env }}"
